# Use a base Node.js image from Docker Hub
FROM node:14-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Angular app
RUN npm run build --prod

# Use nginx to serve the built Angular app
FROM nginx:alpine
COPY --from=0 /app/dist/porsche-app /usr/share/nginx/html
EXPOSE 80

# Start nginx server
CMD ["nginx", "-g", "daemon off;"]
